apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebappproduct
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebappproduct
  template:
    metadata:
      labels:
        app: mywebappproduct
    spec:
      containers:
      - name: mywebappproduct
        image: gcr.io/PROJECT_ID/mywebappproduct:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
